services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGODATA: "$PWD/mongodata"
    ports:
      - 27017:27017

  engine:
    build: ./engine
    restart: unless-stopped
    volumes:
      - ./engine:/engine
    ports:
      - "5000:5000"
    depends_on:
      - mongodb