services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017
    command: --quiet

  engine:
    build: ./engine
    restart: unless-stopped
    volumes:
      - ./engine:/engine
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - engine