FROM python:3.10
WORKDIR /engine
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir pymongo flask flask-cors
ADD server.py server.py
EXPOSE 5000
ENTRYPOINT ["python3.10", "-m", "flask", "--app", "server.py", "run", "--debug", "--host=0.0.0.0"]